name: 3x2pths
channels:
  - conda-forge
  - defaults
dependencies:
  # namaster
  # - python=3.8 # 3.9 is giving problems in miniconda/3
  - numpy<1.20
  - gcc_linux-64
  - gxx_linux-64
  - gfortran_linux-64
  - git
  - namaster
  - healpy
  - pandas
  - pyarrow
  - fitsio
  - pyyaml
  - pip
  # cosmosis
  - openmpi
  - openmp
  - libgomp
  - mpi4py
  - fftw
  - cfitsio
  - gsl
  - lapack
  - blas
  - ipykernel
  - pip:
  #    - -e git+https://github.com/esheldon/healpix_util.git#egg=healpix_util
    - git+https://github.com/esheldon/healpix_util.git
    - git+https://github.com/joezuntz/2point.git
    # https://bitbucket.org/joezuntz/cosmosis/src/2d29d33e64da2d4b0368e19cb9f9a5af559f0294/bin/cosmosis_main.py?at=master#lines-11
    - configparser
    - future
# More utils
    - getdist
    - camb
  # - pyccl
